# Generated by Django 5.2.4 on 2025-08-12 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogs/')),
                ('author', models.CharField(default='Anonymous', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved')], default='pending', max_length=10)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('Microsoft Dynamics', 'Microsoft Dynamics'), ('Odoo', 'Odoo')], max_length=50)),
                ('short_description', models.TextField()),
                ('full_description', models.TextField()),
                ('rating', models.FloatField(default=0.0)),
                ('review_count', models.IntegerField(default=0)),
                ('total_learners', models.IntegerField(default=0)),
                ('course_duration', models.CharField(blank=True, max_length=50)),
                ('assignments_duration', models.CharField(blank=True, max_length=50)),
                ('job_oriented_training', models.BooleanField(default=False)),
                ('support_available', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/')),
                ('video', models.FileField(blank=True, null=True, upload_to='courses/videos/')),
                ('syllabus_link', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstructorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('country_code', models.CharField(default='+91 India', max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('current_city', models.CharField(max_length=100)),
                ('course_topic', models.CharField(max_length=150)),
                ('linkedin_url', models.URLField()),
                ('about_yourself', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('batch_type', models.CharField(choices=[('WEEKDAY', 'Weekday'), ('WEEKEND', 'Weekend'), ('FAST_TRACK', 'Fast Track')], max_length=20)),
                ('title', models.CharField(help_text='Example: Weekdays Regular (Class 1Hr - 1:30Hrs) / Per Session.', max_length=255)),
                ('schedule_details', models.TextField(help_text='Example: (Monday - Friday) Time: 08:00 AM (IST)')),
                ('course_fees', models.IntegerField(blank=True, help_text='Optional: Link to course fees page', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='newapp.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
