# Generated by Django 5.2.4 on 2025-08-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_delete_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorapplication',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
    ]
