# Generated by Django 5.2.4 on 2025-08-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_remove_course_image_course_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.AddField(
            model_name='course',
            name='assignments_duration',
            field=models.CharField(default='0 HRS', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='course_duration',
            field=models.CharField(default='0 HRS', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='job_oriented_training',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.9, max_digits=3),
        ),
        migrations.AddField(
            model_name='course',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='support_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='total_learners',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
