# Generated by Django 5.2.4 on 2025-08-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_fees',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
