# Generated by Django 5.2.4 on 2025-08-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_remove_course_duration_remove_course_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('Microsoft Dynamics', 'Microsoft Dynamics'), ('Odoo', 'Odoo')], default='Please enter the default value as valid Python. ', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='assignments_duration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_duration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='job_oriented_training',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='course',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='support_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_learners',
            field=models.IntegerField(default=0),
        ),
    ]
