# Generated by Django 5.2.4 on 2025-08-02 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_course_category_alter_course_assignments_duration_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DynamicsCourse',
        ),
    ]
