# Generated by Django 5.2.4 on 2025-08-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_delete_dynamicscourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='syllabus_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
