# Generated by Django 5.2.4 on 2025-08-18 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='category',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(default='General', on_delete=django.db.models.deletion.CASCADE, to='newapp.course'),
        ),
    ]
