# Generated by Django 5.2.4 on 2025-08-23 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_alter_blog_image_alter_course_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
    ]
