# Generated by Django 5.2.4 on 2025-08-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_course_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('batch_type', models.CharField(choices=[('WEEKDAY', 'Weekday'), ('WEEKEND', 'Weekend'), ('FAST_TRACK', 'Fast Track')], max_length=20)),
                ('title', models.CharField(help_text='Example: Weekdays Regular (Class 1Hr - 1:30Hrs) / Per Session.', max_length=255)),
                ('schedule_details', models.TextField(help_text='Example: (Monday - Friday) Time: 08:00 AM (IST)')),
                ('course_fees_link', models.URLField(blank=True, help_text='Optional: Link to course fees page', null=True)),
            ],
        ),
    ]
