# Generated by Django 5.2.4 on 2025-08-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0009_upcomingbatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcomingbatch',
            name='course_fees_link',
        ),
        migrations.AddField(
            model_name='upcomingbatch',
            name='course_fees',
            field=models.IntegerField(blank=True, help_text='Optional: Link to course fees page', null=True),
        ),
    ]
