# Generated by Django 5.2.4 on 2025-08-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0014_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
