# Generated by Django 5.2.4 on 2025-08-12 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0017_blog_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
    ]
